"""ABAC policies, requests, attributes, and decisions.

Conditions cover roles, clearance, device type, security state, room,
action, and optional time restrictions."""

from enum import Enum

from pydantic import AliasChoices, BaseModel, Field

from shared.devices import DeviceType, SecurityState


class SubjectType(str, Enum):
    PERSONNEL = "personnel"
    DEVICE = "device"


class ResourceType(str, Enum):
    TELEMETRY = "telemetry"
    ROOM = "room"
    DEVICE = "device"
    PERSONNEL = "personnel"
    IOT_POLICY = "iot_policy"
    ABAC_POLICY = "abac_policy"


class PolicyEffect(str, Enum):
    ALLOW = "allow"
    DENY = "deny"


class Action(str, Enum):
    PUBLISH_ENVIRONMENTAL_TELEMETRY = "publish_environmental_telemetry"
    PUBLISH_SMOKE_TELEMETRY = "publish_smoke_telemetry"
    PUBLISH_PDU_TELEMETRY = "publish_pdu_telemetry"
    CONTROL_HVAC = "control_hvac"
    CONTROL_PDU = "control_pdu"
    CONTROL_DOOR = "control_door"
    REQUEST_DOOR_ACCESS = "request_door_access"

    CREATE_ROOM = "create_room"
    EDIT_ROOM = "edit_room"
    DELETE_ROOM = "delete_room"
    REGISTER_DEVICE = "register_device"
    EDIT_DEVICE = "edit_device"
    DELETE_DEVICE = "delete_device"
    CREATE_PERSONNEL = "create_personnel"
    EDIT_PERSONNEL = "edit_personnel"
    CREATE_IOT_POLICY = "create_iot_policy"
    EDIT_IOT_POLICY = "edit_iot_policy"
    DELETE_IOT_POLICY = "delete_iot_policy"
    CREATE_ABAC_POLICY = "create_abac_policy"
    EDIT_ABAC_POLICY = "edit_abac_policy"
    DELETE_ABAC_POLICY = "delete_abac_policy"
    RESET_SECURITY_STATE = "reset_security_state"


class SubjectAttributes(BaseModel):
    subject_id: str
    subject_type: SubjectType
    role: str | None = None
    clearance: int | None = Field(default=None, ge=0, le=5)
    device_type: DeviceType | None = None
    room_id: str | None = None
    security_state: SecurityState | None = None


class ResourceAttributes(BaseModel):
    resource_id: str
    resource_type: ResourceType
    room_id: str | None = None
    device_type: DeviceType | None = None
    security_state: SecurityState | None = None


class RequestContext(BaseModel):
    hour: int | None = Field(default=None, ge=0, le=23)


class PolicyRequest(BaseModel):
    subject: SubjectAttributes
    action: Action
    resource: ResourceAttributes
    context: RequestContext = RequestContext()


class PolicyFields(BaseModel):
    """Editable fields shared by created and persisted ABAC policies."""

    name: str
    effect: PolicyEffect
    action: Action
    subject_type: SubjectType
    resource_type: ResourceType

    subject_roles: list[str] | None = Field(
        default=None, validation_alias=AliasChoices("subject_roles", "subject_role")
    )
    minimum_clearance: int | None = Field(default=None, ge=0, le=5)
    subject_device_type: DeviceType | None = None
    resource_device_type: DeviceType | None = None
    require_same_room: bool = False
    allowed_subject_security_states: list[SecurityState] | None = None
    allowed_resource_security_states: list[SecurityState] | None = None
    start_hour: int | None = Field(default=None, ge=0, le=23)
    end_hour: int | None = Field(default=None, ge=0, le=23)
    priority: int = 5
    enabled: bool = True


class PolicyCreate(PolicyFields):
    """Creation payload; policy_id is generated by the gateway."""

    pass


class Policy(PolicyFields):
    """Stored ABAC policy with gateway-assigned identifier."""

    policy_id: str


class PolicyDecision(BaseModel):
    allowed: bool
    effect: PolicyEffect
    policy_id: str | None = None
    policy_name: str | None = None
    reason: str
